version = 1

[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  runtime = "node"
  environment = ["browser", "node"]
  frameworks = ["react", "next"]

[[analyzers]]
name = "typescript"
enabled = true
  [analyzers.meta]
  runtime = "node"
  environment = ["browser", "node"]
  frameworks = ["react", "next"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

# Community analyzers
[[analyzers]]
name = "eslint"
enabled = true

[[analyzers]]
name = "prettier"
enabled = true

[[analyzers]]
name = "prisma"
enabled = true
